# fly.toml app configuration file generated for shubham on 2023-05-05T18:30:48+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "shubham"
primary_region = "cdg"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
