# fly.toml app configuration file generated for lingering-silence-5862 on 2023-05-05T13:48:27+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "lingering-silence-5862"
primary_region = "sin"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
