databases:
  - name: MG_API
    databaseName: MG_API
    user: MG_API

services:
  - type: web
    name: MG_API
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: MG_API
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false